# Generated by Django 3.1.7 on 2021-02-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210221_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes', to='product.Size'),
        ),
    ]
