# Generated by Django 3.1.7 on 2021-02-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
